AllCops:
  Exclude:
    - 'bin/*'
    - 'config/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Enabled: false
